[project]
name = "news-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg2-binary",
    "requests",
    "openai",
    "numpy",
    "crewai",
    "crewai-tools",
    "mcp"
]
